---
title: "measlesvaccinedata"
format: html
---

# Install Packages

```{r}
library(ggplot2)
library(tidyr)
library(dplyr)
library(janitor)
library(gtsummary)
```

# Dataset

## Loading Dataset

```{r}
# load dataset
measles <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2020/2020-02-25/measles.csv')

# make sure dataset loaded correctly
head(measles)
```

## Cleaning/Wrangling Dataset

```{r}
measles0 <- measles |> select(!(lat:lng))
measles1 <- data.frame(unique(measles0))
measles2 <- measles1 |> filter(!is.na(measles1$state))
measles3 <- measles2 |> filter(!is.na(measles2$type))
measles4 <- measles3 |> filter(!is.na(measles3$enroll))
measles5 <- measles4 |> filter(measles4$mmr != -1)
measles6 <- measles5 |> filter(measles5$type != "Kindergarten")
```

# Visualization Test

```{r}
boxplot(mmr ~ type, data = measles6)
boxplot(mmr ~ state, data = measles6)
plot(mmr ~ enroll, data = measles6)
```

# Modeling

```{r}
# no transformations
lm1 <- lm(mmr ~ type + state + enroll, data = measles6)
summary(lm1)
plot(lm1, 1:2)
```

```{r}
# log transformation on response
lm2 <- lm(log(mmr) ~ type + state + enroll, data = measles6)
summary(lm2)
plot(lm2, 1:2)
```

## Remove Outliers

```{r}
ind1 <- which(abs(rstandard(lm2)) > 2)
measles6[ind1, ]
measles7 <- measles6[-ind1, ]
```

```{r}
lm3 <- lm(log(mmr) ~ type + state + enroll, data = measles7)
summary(lm3)
plot(lm3, 1:2)
```

```{r}
lm4 <- lm(sqrt(mmr) ~ type + state + enroll, data = measles7)
summary(lm4)
plot(lm4, 1:2)
```

```{r}
# remove Colorado
measles8 <- measles7 |> filter(measles7$state != "Colorado")

lm5 <- lm(sqrt(mmr) ~ type + state + enroll, data = measles8)
summary(lm5)
plot(lm5, 1:2)
```

```{r}
lm6 <- lm(sqrt(mmr) ~ type + state + enroll + type*state + type*enroll + state*enroll, data = measles8)
summary(lm6)
plot(lm6, 1:2)
```

```{r}
lm7 <- lm(sqrt(mmr) ~ type + state + poly(enroll, 8), data = measles8)
summary(lm7)

# stop at 8th order -> insignificant
```

```{r}
# stick with 7th order for enroll

lm8 <- lm((mmr)^8 ~ type + state + poly(enroll, 7), data = measles8)
summary(lm8)
plot(lm8, 1:2)
```

```{r}
# add interactions

lm9 <- lm((mmr)^8 ~ type + state*poly(enroll, 7), data = measles8)
summary(lm9)
plot(lm9, 1:2)
```

```{r}
n <- nrow(measles8)
step(lm9, trace = 2)
```

```{r}
lm10 <- lm((mmr)^13 ~ type + state*poly(enroll,7), data = measles6)
summary(lm10)
plot(lm10, 1:2)
AIC(lm10)
```

# Starting from Scratch

Research question changed to only focus on Colorado

```{r}
measles_ut <- measles6 |> filter(measles6$state == "Utah")

boxplot(mmr ~ type, data = measles_ut)
plot(mmr ~ enroll, data = measles_ut)
```

```{r}
# linear model
lm_ut <- lm(mmr ~ type + enroll, data = measles_ut)
summary(lm_ut)
```

```{r}
# remove outliers
ind1 <- which(abs(rstandard(lm_ut)) > 2)
measles_ut[ind1, ]
measles_ut2 <- measles_ut[-ind1, ]
```

```{r}
measles_ca <- measles6 |> filter(measles6$state == "California")

boxplot(mmr ~ type, data = measles_ca)
plot(mmr ~ enroll, data = measles_ca)
```

```{r}
lm_ca <- lm(mmr ~ type + enroll, data = measles_ca)
summary(lm_ca)
```

```{r}
# remove outliers
ind1 <- which(abs(rstandard(lm_ca)) > 2)
measles_ca[ind1, ]
measles_ca2 <- measles_ca[-ind1, ]
```

```{r}
boxplot(mmr ~ type, data = measles_ca2)
plot(mmr ~ enroll, data = measles_ca2)
```
